### ISSUE TITLE
Process to deploy and run in Cloud foundry

### ISSUE THREAD

**Issue by pradeepkusingh** [skibum55/cf-locust#1]
Thanks for this example, can you please provide little bit more details, how to deploy and run it on Cloud foundry. I am from java and spring boot background and used the mostly manifest file to push in cf.

**Comment by adudiapis** [comment]
Hi @skibum55 , I would like to here about it too. I am trying to deploy this docker container to CF but it's failing with: 
`2019-04-02T15:23:02.94-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,949] a1289ee6-ae03-4e17-66b3-2d4c/INFO/locust.main: Starting Locust 0.11.0
   2019-04-02T15:23:02.95-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,959] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr: Traceback (most recent call last):
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,959] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr:
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,960] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr: File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,960] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr:
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,960] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr: File "/usr/local/lib/python3.6/site-packages/locust/web.py", line 168, in start
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR     app, log=None).serve_forever()
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,960] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr:
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,961] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr: File "/usr/local/lib/python3.6/site-packages/gevent/baseserver.py", line 367, in serve_forever
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR     self.start()
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,961] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr:
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,961] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr: File "/usr/local/lib/python3.6/site-packages/gevent/baseserver.py", line 305, in start
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR     self.init_socket()
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,961] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr:
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,961] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr: File "/usr/local/lib/python3.6/site-packages/gevent/pywsgi.py", line 1490, in init_socket
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR     StreamServer.init_socket(self)
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,961] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr:
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,961] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr: File "/usr/local/lib/python3.6/site-packages/gevent/server.py", line 146, in init_socket
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR     self.socket = self.get_listener(self.address, self.backlog, self.family)
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,961] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr:
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,962] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr: File "/usr/local/lib/python3.6/site-packages/gevent/server.py", line 157, in get_listener
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR     return _tcp_listener(address, backlog=backlog, reuse_addr=cls.reuse_addr, family=family)
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,962] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr:
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,962] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr: File "/usr/local/lib/python3.6/site-packages/gevent/server.py", line 252, in _tcp_listener
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR     sock = GeventSocket(family=family)
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,962] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr:
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,962] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr: File "/usr/local/lib/python3.6/site-packages/gevent/_socket3.py", line 100, in __init__
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR     self._sock = self._gevent_sock_class(family, type, proto, fileno)
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,962] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr:
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,962] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr: OSError: [Errno 97] Address family not supported by protocol
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,963] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr:
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,963] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr: 2019-04-02T19:23:02Z
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,963] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr:
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,963] a1289ee6-ae03-4e17-66b3-2d4c/ERROR/stderr: <Greenlet at 0x7fea66aada48: start([<class 'locust.WebsiteUser'>], <Values at 0x7fea669ade80: {'host': None, 'web_hos)> failed with OSError
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,963] a1289ee6-ae03-4e17-66b3-2d4c/INFO/locust.main: Shutting down (exit code 0), bye.
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,963] a1289ee6-ae03-4e17-66b3-2d4c/INFO/locust.main: Cleaning up runner...
   2019-04-02T15:23:02.96-0400 [APP/PROC/WEB/0] ERR [2019-04-02 19:23:02,964] a1289ee6-ae03-4e17-66b3-2d4c/INFO/locust.main: Running teardowns...`

I tried to change port with -P to 5000 and 8080. Not sure what's wrong. Appreciate your input.
Thanks.
